### ISSUE TITLE
readme

### ISSUE THREAD

**Issue by artamonJr** [parunkov/toxin#1]
1. Без 100 грамм не разберешь, что кроется под названием проекта 'work'. Нужно придумать нормально название
2. Куда ведет эта ссылка?
![image](https://user-images.githubusercontent.com/46949445/77409749-d6a23f00-6dca-11ea-8b19-0fb93d412052.png)
3. github.com - сайт. https://parunkov.github.io/work/build/ - не сайт, а демо-страница. В целом то это сайт да, но немного не так написано
4. Ты хорошо отрефакторил код по стандартам? В реадми уже 1 пункт не соблюден
![image](https://user-images.githubusercontent.com/46949445/77410153-87a8d980-6dcb-11ea-89af-36a52301daca.png)

**Comment by parunkov** [comment]
Переименовал проект в toxin (по названию сайта). Убрал топик. Переписал readme.md. Проверил разворачивание в новую папку.

**Comment by madnessJs** [comment]
Переоткрой коммиты, я сам буду закрывать после проверки)

**Comment by madnessJs** [comment]
1. Также пункт стандартов
![image](https://user-images.githubusercontent.com/46949445/77513190-9a7fe480-6e85-11ea-813e-ad6d269227e1.png)
2. Также
![image](https://user-images.githubusercontent.com/46949445/77513263-ba170d00-6e85-11ea-8898-d10a6cb9d5af.png)
3. Прописать команды для клонирования репозитория
4. Примеры кода обрамить в markdown code

**Comment by artamonJr** [comment]
Тут лучше не указывать столь точно 'git bash'. А если у пользоваться windows shell? Ему нельзя склонировать проект?)) И написать все возможные способы, не только https
![image](https://user-images.githubusercontent.com/46949445/77647609-c380a200-6f77-11ea-829c-c6611e7898f1.png)

**Comment by parunkov** [comment]
У меня только двумя способами получилось клонировать.

**Comment by artamonJr** [comment]
![image](https://user-images.githubusercontent.com/46949445/80945715-18280000-8df5-11ea-9af3-6fa190ac934f.png)
Исправь на "Демо страница"
