### ISSUE TITLE
basic iteration (html, css, bem)

### ISSUE THREAD

**Issue by artamonJr** [parunkov/toxin#10]
Хорошая работа проделана по улучшению проекта, так держать!
Не красота ли стала, без всяких space, active и тд))

У тебя keywords одинаков на всех страницах сайта, такого быть не должно. И почитай еще за keywords, тк ты не особо понимаешь назначение этого тега. Разве, когда я пишу в поисковике "отзывы об отеле" я хочу попасть на главную страницу сайта Toxin?

Во-первых - плохое название модификатора, во-вторых - нужно это убрать, 100%. Хедеру все равно, на каком языке в нем написано, а стили в хедере одинаковые на всех страницах)
![image](https://user-images.githubusercontent.com/46949445/83251659-97211600-a1b2-11ea-897a-1c176e53c8cf.png)

Не может быть на теге класса элемента без класса блока, т.е. если есть .block__elem, то должен быть и .block, это первое
Второе, почитай про то, как сделать элемент img доступным для незрячих пользователей, тк это ну просто best practice
![image](https://user-images.githubusercontent.com/46949445/83252201-7efdc680-a1b3-11ea-974c-2f8944a883a8.png)

Какую роль у тебя выполняет кнопка в этом контексте? Отправляет форму?
![image](https://user-images.githubusercontent.com/46949445/83252305-ae143800-a1b3-11ea-9d08-a46f394c3d6d.png)

Можно попробовать избавиться от лишней обертки wrapper?
![image](https://user-images.githubusercontent.com/46949445/83253155-2a5b4b00-a1b5-11ea-817e-f40cc1150aed.png)

Пункт без подменю ведь, не?)
![image](https://user-images.githubusercontent.com/46949445/83253213-452dbf80-a1b5-11ea-81d3-27949d467154.png)

По бэм - не использовать в стилях обращения по тегам
![image](https://user-images.githubusercontent.com/46949445/83253336-7e662f80-a1b5-11ea-9a28-8f8e7f494056.png)

Уверен, что тут модификаторы нужны и на пункте меню и на ссылке?
![image](https://user-images.githubusercontent.com/46949445/83253855-5d520e80-a1b6-11ea-9228-b16cc9482bd4.png)

Плохое название элемента. Можно попробовать посмотреть в сторону модификаторов)
![image](https://user-images.githubusercontent.com/46949445/83254077-cfc2ee80-a1b6-11ea-8f79-2f6cac55a4ae.png)

Думаешь тут нужен header__btn-wrapper? Обертки header__btn не достаточно?
![image](https://user-images.githubusercontent.com/46949445/83254537-976fe000-a1b7-11ea-8a07-f8765948c02d.png)

Тут точно булевый модификатор не к месту и low-light ну так себе, нужно преименовать
![image](https://user-images.githubusercontent.com/46949445/83254624-c5552480-a1b7-11ea-971c-545924c41550.png)

inner - adjective, не пойдет)
![image](https://user-images.githubusercontent.com/46949445/83254753-f2093c00-a1b7-11ea-8071-87ee34a9a6ac.png)

Что за low?) Не пойдет)
![image](https://user-images.githubusercontent.com/46949445/83254900-2250da80-a1b8-11ea-9387-21419e06517c.png)

Аналогично с хедером - нужно избавиться от rus
Назови элементы более осознанно, block-1 и block-2 не годится
![image](https://user-images.githubusercontent.com/46949445/83255260-bfac0e80-a1b8-11ea-8862-5448a0500fdc.png)

Вот footer__navigation отличное название, но у 1 и 3 элемента - ужс)
![image](https://user-images.githubusercontent.com/46949445/83255355-ef5b1680-a1b8-11ea-93f8-e65f1cdba856.png)

Лучше не называть такие элементы как header, тк header это что-то более большое, по типу блока. Обычно этот элемент называется titile/subtitle
Почему header list? Разве это заголовок списка?
Нельзя прыгать в иерархии заголовков? Т.е. если у тебя есть h3, то должны быть и h1 и h2, но h2 я у тебя не обнаружил на странице
![image](https://user-images.githubusercontent.com/46949445/83255851-e0289880-a1b9-11ea-8896-aa19927fcb62.png)

Подбери более подходящие теги вместо div)
![image](https://user-images.githubusercontent.com/46949445/83257594-60043200-a1bd-11ea-8021-3138b0d92ad8.png)

Попробуй упростить компонент input, тк он у тебя явно переусложнен
![image](https://user-images.githubusercontent.com/46949445/83257426-0ac82080-a1bd-11ea-803f-544816f47ce1.png)

**Comment by parunkov** [comment]
button не обязательно внутри формы должен быть, можно и без формы использовать (где нужна стандартная кнопка).

**Comment by parunkov** [comment]
Уверен, что тут модификаторы нужны и на пункте меню и на ссылке?
У меня без них скрипт не работает.

**Comment by artamonJr** [comment]
Ну вот, хедер уже более менее.

> button не обязательно внутри формы должен быть, можно и без формы использовать (где нужна стандартная кнопка)

А чтобы это была стандартная кнопка, что нужно сделать?

Зачем модификатор main?
![image](https://user-images.githubusercontent.com/46949445/83729776-cb805080-a650-11ea-9734-37e2718dab40.png)

> У меня без модификатора на пункте меню скрипт не работает

Нужно сделать, так чтобы работал) Тут достаточно, на пункт меню повесить модификатор)

Плохое название модификаторов. Либо измени на подходящее, либо, что еще лучше, избавься от них, тк можно сделать на порядок проще. Посмотри в сторону отношения родитель ->ребенок в css селекторах)
![image](https://user-images.githubusercontent.com/46949445/83730130-4fd2d380-a651-11ea-9784-3e30e7e0155e.png)
![image](https://user-images.githubusercontent.com/46949445/83730187-624d0d00-a651-11ea-9d67-ac13bcda71f7.png)

Опять по модификаторам)
Модификатор frame? Переводится название класса как "кнопка рамка", а название модификатора должно отвечать на вопросы "как выглядит?, какой?" и тд. Поэтому этот модификатор неверный. Почитай еще про модификаторы в бэм.
Модификатор size_small-frame тоже неправильный. У тебя ключ модификатора size, который описывает размер кнопки, верно? Почему у него значение small-frame?
![image](https://user-images.githubusercontent.com/46949445/83730684-18185b80-a652-11ea-826c-e6552f26c8ea.png)

Тут опять дублирование классов. Нужно сделать так, чтобы на span'е не дублировался класс модификатора.
И может inner-block переименовать в что-то более подходящее для текста в кнопке?
![image](https://user-images.githubusercontent.com/46949445/83731538-611cdf80-a653-11ea-8b2f-733a7d002c78.png)

Зачем тут ненужный и неправильный модификатор "bottom" на контейнере? Можно же воспользововаться замечательным каскадом в css, чтобы не переусложнять разметку классами. Почему не написать .social-section .container {}?
![image](https://user-images.githubusercontent.com/46949445/83732114-4434dc00-a654-11ea-9e04-14ffd2e7ad4b.png)

footer__column точно не лишний здесь?
![image](https://user-images.githubusercontent.com/46949445/83732196-60387d80-a654-11ea-81e0-5144e76cc9ab.png)

social-list, social-item - отлично. social? Социальный? Что за название?)
Булевый модификатор twitter, уверен? У тебя 3 разных социальных ссылки, поэтому 3 разных темы для оформления ссылок, ага?)
![image](https://user-images.githubusercontent.com/46949445/83732348-983fc080-a654-11ea-854c-c8f1781b2232.png)

Футер подписаться?
![image](https://user-images.githubusercontent.com/46949445/83732637-05ebec80-a655-11ea-99e8-3acda976079f.png)

Плохой модификатор
![image](https://user-images.githubusercontent.com/46949445/83732820-4ea3a580-a655-11ea-84f8-f1b85d1938ea.png)

Название элемента input не очень правильное, тк input = ввод, а ввод может быть любой. В данном случае лучше было бы использовать text-input/field
Модификатор arrow не годится
Значение атрибута name не годится)
![image](https://user-images.githubusercontent.com/46949445/83732990-8f9bba00-a655-11ea-890f-77b240af110d.png)

Модификатор purple не годится
![image](https://user-images.githubusercontent.com/46949445/83733131-cbcf1a80-a655-11ea-8b1e-1483059382ce.png)

footer__column не пойдет + мы не используем цифры в названиях классов
![image](https://user-images.githubusercontent.com/46949445/83734117-3f255c00-a657-11ea-8fe8-da010fb818b4.png)

Не годится модификатор menu
![image](https://user-images.githubusercontent.com/46949445/83734402-a04d2f80-a657-11ea-88a5-2e4853f5e7d5.png)

**Comment by parunkov** [comment]
.header__navigation-list_main используется в скрипте - на странице Headers & Footers два хедера, использую для выбора хедера для открытия при нажатии на бургер. На Landing page работает без него.

**Comment by artamonJr** [comment]
Во-первых, не может быть модификатора модификатора with-submenu-opened, да еще и неправильной записи (-opened, вместо _opened)
Во-вторых, что значит opened на пункте меню? Он разве открыт? Расширен - да, но не открыт
В-третьих, зачем добавлять уйму модификаторов на элементы? Можно ограничиться модификатором на пункте меню и использовать css каскад
![image](https://user-images.githubusercontent.com/46949445/84004130-c2a2be00-a973-11ea-8abe-b3f167a69c64.png)

Если есть еще где-то такое - убери. Понимаешь почему?
![image](https://user-images.githubusercontent.com/46949445/84005110-46a97580-a975-11ea-8e1b-9e4ae9977ef8.png)

Уже обсуждали... Что здесь не так?
![image](https://user-images.githubusercontent.com/46949445/84005408-c46d8100-a975-11ea-943d-738c36b6a352.png)

Плохой модификатор)
![image](https://user-images.githubusercontent.com/46949445/84005549-f4b51f80-a975-11ea-8a55-562dcdae82e4.png)

Убери пустой атрибут value
![image](https://user-images.githubusercontent.com/46949445/84005670-2928db80-a976-11ea-8bb8-c26b7c1000c3.png)

Плохой модификатор)
![image](https://user-images.githubusercontent.com/46949445/84005705-38a82480-a976-11ea-9f40-788e86ca6c82.png)

Эти элементы не переусложняют твою разметку?
![image](https://user-images.githubusercontent.com/46949445/84006171-f29f9080-a976-11ea-829c-29904dc901de.png)

Ты выделил этот блок в отдельный, что правильно. Почему стили landing__form-wrapper влияют на этот блок?
![image](https://user-images.githubusercontent.com/46949445/84006363-4316ee00-a977-11ea-825c-9939ec48575b.png)

Можно подумать, возможно можно полностью отказаться от этого элемента?
![image](https://user-images.githubusercontent.com/46949445/84006533-925d1e80-a977-11ea-8c83-36e1be84497b.png)

**Comment by parunkov** [comment]
Если есть еще где-то такое - убери. Понимаешь почему?
Как я понял, нельзя менять стили блока,  вложенного в другой блок. А если я убрал модификаторы хедера и футера, как мне их стили поменять?

**Comment by parunkov** [comment]
От landing__form-wrapper по моему нельзя отказаться. Внешние размеры блока нельзя в нем задавать, обертка нужна.

**Comment by parunkov** [comment]
viewport из стандартов взят.

**Comment by artamonJr** [comment]
> их стили поменять?

чьи?

Ключ модификатора icon не очень удачный. Обычно используется theme в таких случаях
![image](https://user-images.githubusercontent.com/46949445/84146309-2dcbbd80-aa64-11ea-9bad-e844c3adfc5e.png)

Почему решил выделить инпут в секцию?
![image](https://user-images.githubusercontent.com/46949445/84146546-8307cf00-aa64-11ea-9da0-ecfa0b811ec1.png)

Не используй отрицательные margin
![image](https://user-images.githubusercontent.com/46949445/84146804-ec87dd80-aa64-11ea-9092-4e04ab6da345.png)

> От landing__form-wrapper по моему нельзя отказаться. Внешние размеры блока нельзя в нем задавать, обертка нужна.

А что значит "внешний размер"?
Избавится можно, подумай как. Просто у тебя неправильно составлена структура отступов

**Мы не используем инлайн стили**
![image](https://user-images.githubusercontent.com/46949445/84153458-93bd4280-aa6e-11ea-9bf5-e473a2d6043a.png)

В чем ошибка по бэм?
![image](https://user-images.githubusercontent.com/46949445/84153488-9fa90480-aa6e-11ea-92f0-3ca1e06b61d4.png)

Хорошо, что выделил datepicker в отдельный компонент. Вот эти два элемента нужно выделить в отдельный компонент, тк они используются как единое целое и в форме поиска номера и в форме подтверждения бронирования
![image](https://user-images.githubusercontent.com/46949445/84154102-573e1680-aa6f-11ea-95cd-3b54b4d9bcaf.png)

Тут неверно реализовано. У тебя компонент button может быть либо кнопкой, либо ссылкой, но никак не div'ом
![image](https://user-images.githubusercontent.com/46949445/84154619-011da300-aa70-11ea-8b3c-2b3232e79f8d.png)

Плохой модификатор
![image](https://user-images.githubusercontent.com/46949445/84154734-25797f80-aa70-11ea-9327-843ba8997c19.png)

Это нужно убрать
![image](https://user-images.githubusercontent.com/46949445/84154800-37f3b900-aa70-11ea-8086-03f6a02ad4e3.png)
![image](https://user-images.githubusercontent.com/46949445/84156024-b13fdb80-aa71-11ea-9c5e-e18022dc4548.png)

Уверен что тут h3 подходящий тег?
![image](https://user-images.githubusercontent.com/46949445/84155948-9d947500-aa71-11ea-8541-f01b26827050.png)

**Comment by parunkov** [comment]
Вижу, убрал, но все равно вопрос: чьи?
В футере нормально все без каскада, а в хедере отступы разные в русской и английской версиях.
Без каскада получается так:
![Скрин](https://user-images.githubusercontent.com/48278719/84226377-083dc300-aafb-11ea-870a-f9a51199ec0d.jpg)

**Comment by parunkov** [comment]
Почему решил выделить инпут в секцию?
Часть формы, имеет заголовок.

**Comment by artamonJr** [comment]
> в хедере отступы между пунктами меню разные в русской (20px) и английской (30px) версиях

Действительно... Огрех макета. Оставь так как есть (20px), кривой макет - не твоя забота)

> Почему решил выделить инпут в секцию?
Часть формы, имеет заголовок.

Во-первых, заголовка у этой секции нет
Во-вторых, ну это никак не секция. Секцией может быть, к примеру, это:
![image](https://user-images.githubusercontent.com/46949445/84367260-a48bc680-abdc-11ea-8ee1-cd5e89f43cfb.png)
но один инпут это не секция

Блокам нельзя задавать внешние размеры (margin: auto)
![image](https://user-images.githubusercontent.com/46949445/84368246-fc76fd00-abdd-11ea-8f0d-16975f62f7af.png)

Что за компонент inputs-block? Какую функцию он несет в себе? В корне неверно сделано. У тебя ведь есть компонент дропдаун, который может использоваться и используется (на странице комнат) где угодно, а есть календарь.
![image](https://user-images.githubusercontent.com/46949445/84368569-64c5de80-abde-11ea-843a-8f629784a392.png)
Этот компонент нужно разбить на два
![Снимок экрана от 2020-06-11 12-26-02](https://user-images.githubusercontent.com/46949445/84369197-2a107600-abdf-11ea-8a6a-ef5ede77cf77.png)

Обычно, для таких случаев, используется элемент, название которого совпадает с названием блока. Для примера - .header__button -> .button
![image](https://user-images.githubusercontent.com/46949445/84369436-7c519700-abdf-11ea-9dfd-f7f55eccf74e.png)

Исправь название модификатора)
![image](https://user-images.githubusercontent.com/46949445/84369513-9ee3b000-abdf-11ea-9225-069ee061e96c.png)

Вот тут, section нормально подходит. Только зачем тебе модификатор theme_peoples? Дропдауны по стилю у тебя не различаются
![image](https://user-images.githubusercontent.com/46949445/84369726-f4b85800-abdf-11ea-9a08-b47f74b491d6.png)

Тут опять смешение стилей
![image](https://user-images.githubusercontent.com/46949445/84369801-0ef23600-abe0-11ea-9124-cd5ffa261e91.png)

Неправильно делаешь отступы между блоками. У тебя задача - сделать отступ между "Гостями" и "Кнопкой". Ты делаешь добавляя margin-bottom элементу внутри дропдауна. Это неверно! Отступ должен быть у обертки дропдауна или обертки кнопки. В данном случае, у inputs-block
![image](https://user-images.githubusercontent.com/46949445/84370119-7c05cb80-abe0-11ea-90d6-aead046da195.png)
p.s. ага, вижу что отступ у обертки кнопки, тогда вот это что?
![image](https://user-images.githubusercontent.com/46949445/84370223-a3f52f00-abe0-11ea-9078-8b2bd21b071d.png)

Это не заголовок
![image](https://user-images.githubusercontent.com/46949445/84370310-bec7a380-abe0-11ea-8a37-21c60b2040e9.png)

Убери это, я же просил)
![image](https://user-images.githubusercontent.com/46949445/84370383-d9018180-abe0-11ea-8432-cf346764b6f8.png)

Дропдаун переусложнен как-то, попробуй подумать над упрощением. Зачем тебе dropdown__container?
![image](https://user-images.githubusercontent.com/46949445/84370905-955b4780-abe1-11ea-949e-5a21722a97da.png)

**Comment by parunkov** [comment]
Только зачем тебе модификатор theme_peoples? Дропдауны по стилю у тебя не различаются
Почему не различаются? У одного есть кнопки внизу, у другого нет. Текст и плейсхолдеры разные.

**Comment by artamonJr** [comment]
> Почему не различаются? У одного есть кнопки внизу, у другого нет. Текст и плейсхолдеры разные

Есть кнопки и нет кнопок, это не тема дропдауна. По виду, еще раз, они у тебя не различаются. Логику, нужно ли добавлять кнопки, ты должен разруливать в pug файле блока. У тебя это вроде и реализовано сейчас (аргумент clear в дропдауне). Атрибуты инпута никак не связаны с темой оформления.

Исправь ключ модификатора у кнопки
![image](https://user-images.githubusercontent.com/46949445/84761177-ba7cfb00-afd1-11ea-9e72-be66133579ec.png)

Почему был выбран тег span здесь?
![image](https://user-images.githubusercontent.com/46949445/84761225-d1235200-afd1-11ea-834a-faa346f033dc.png)

Заполни name
Переименуй название элемента. Почему selection?
Также убери пробелы в названии класса
![image](https://user-images.githubusercontent.com/46949445/84761498-28292700-afd2-11ea-9828-c8525c3737ab.png)

Переименуй название элемента и выбери более семантичный тег для этого элемента
![image](https://user-images.githubusercontent.com/46949445/84761690-74746700-afd2-11ea-84da-f0083104fb56.png)

Почему при открытии дропдауна на элемент вешаются 2 класса? Одного недостаточно?
![image](https://user-images.githubusercontent.com/46949445/84761777-9a9a0700-afd2-11ea-85b3-0f6666f1b98c.png)

Слишком длинные названия классов, поработай над исправлением.
Зачем тебе дата атрибут id на элементе?
![image](https://user-images.githubusercontent.com/46949445/84762109-0e3c1400-afd3-11ea-8cb8-7cce906383c7.png)

У тебя две одинаковые по виду кнопки. Зачем давать им разные имена классов? Чтобы дублировать css код? Подумай в сторону модификаторов
![image](https://user-images.githubusercontent.com/46949445/84762405-712dab00-afd3-11ea-9371-ce0fb3ca8464.png)

Зачем тебе тут тег i?
![image](https://user-images.githubusercontent.com/46949445/84763038-4abc3f80-afd4-11ea-9dc2-ce796ae5a4ca.png)

Какую функцию выполняет эта кнопка?
![image](https://user-images.githubusercontent.com/46949445/84763086-5c054c00-afd4-11ea-954e-57f8fa6b8c52.png)

Исправь название класса
![image](https://user-images.githubusercontent.com/46949445/84763145-6c1d2b80-afd4-11ea-8ff1-ceccb4130d52.png)

Что не так с этим блоком по бэм?
![image](https://user-images.githubusercontent.com/46949445/84763382-c1f1d380-afd4-11ea-94ae-23fa6b46f968.png)

Блок дат? Не слишком описательно
![image](https://user-images.githubusercontent.com/46949445/84763410-d0d88600-afd4-11ea-9e03-d725f62fc045.png)

Не нужно плодить классы в коде. Разметка должна читаться просто. Зачем тебе тут два разных класса?
![image](https://user-images.githubusercontent.com/46949445/84763961-ac30de00-afd5-11ea-8c35-88292767bf21.png)

Почему этот компонент input? Это же вроде dropdown?
![image](https://user-images.githubusercontent.com/46949445/84764057-ce2a6080-afd5-11ea-86b3-bf2577b7fbe4.png)

Не используем inline стили, я говорил уже
![image](https://user-images.githubusercontent.com/46949445/84764264-1b0e3700-afd6-11ea-8aa2-f2e48e93d6d8.png)

При отправке этой формы ты хочешь получить все поля из этой формы на стороне сервера?
Тебе важно знать, например, желаемую дату "Прибытие", чтобы показать пользователю релевантные к его запросу номера?
![image](https://user-images.githubusercontent.com/46949445/84764431-63c5f000-afd6-11ea-84b4-f94946c3d2a4.png)

По-хорошему, это должна быть кнопка. Прикольно, что сделано ссылкой, но лучше выработать в себе привычку использовать семантические теги.
![image](https://user-images.githubusercontent.com/46949445/84764818-fbc3d980-afd6-11ea-959f-6ae45ecdd566.png)

**Comment by parunkov** [comment]
Почему был выбран тег span здесь?
Строчный элемент без лишних функций, проще чем label.

**Comment by parunkov** [comment]
Почему этот компонент input? Это же вроде dropdown?
Компонент input тоже ведь подходит сюда - это ведь инпуты. Зачем создавать новый компонент, если можно использовать уже существующий?

**Comment by artamonJr** [comment]
**Исправь ключ модификатора у кнопки**.
*3-ий раз пишу об этом замечании*
Что за witch?
И зачем тут два модификатора?
![image](https://user-images.githubusercontent.com/46949445/85026557-7df00180-b181-11ea-8ea6-8327d37d8c2b.png)

> Строчный элемент без лишних функций, проще чем label

А у label какие лишние функции?

input-button? Это разве кнопка инпута?
![image](https://user-images.githubusercontent.com/46949445/85027222-58172c80-b182-11ea-8b64-9adf0b3e8597.png)

Что за witch?) Странное название... до появления модификатора дропдаун был без меню? Нужно переименовать
![image](https://user-images.githubusercontent.com/46949445/85027384-88f76180-b182-11ea-9700-2dd9aae4a08d.png)

Опять модификаторы. Нужно определенно поработать над пониманием БЭМ, у тебя с этим плоховато. Но, уже намного лучше, чем в начале обучения.
Плохие названия модификаторов, нужно поправить
![image](https://user-images.githubusercontent.com/46949445/85028086-54d07080-b183-11ea-8f06-ba3ce8e7edcb.png)
![image](https://user-images.githubusercontent.com/46949445/85028106-58fc8e00-b183-11ea-949f-c6fbe600cb4e.png)

Блок настроек? Какие там настройки, если там две кнопки?
![image](https://user-images.githubusercontent.com/46949445/85028232-7af61080-b183-11ea-8aa4-857c033b9a93.png)

> Компонент input тоже ведь подходит сюда - это ведь инпуты. Зачем создавать новый компонент, если можно использовать уже существующий?

Дропдаун включает в себя инпут, так правильнее. А зачем тебе создавать новый компонент? У тебя есть компонент dropdown уже. Это он же, просто без контейнера с каунтерами

Название получше, но ведь можно и проще назвать. Как насчет calendar?
![image](https://user-images.githubusercontent.com/46949445/85028681-0f607300-b184-11ea-8d9d-d8f5f826cc2d.png)

Можно выпилить одно из двух?
![image](https://user-images.githubusercontent.com/46949445/85029811-6155c880-b185-11ea-8563-89b3c3002df8.png)

Это тоже не блок настроек
![image](https://user-images.githubusercontent.com/46949445/85029891-79c5e300-b185-11ea-9d8e-3df54507e152.png)

Эти кнопка - отдельный компонент
![image](https://user-images.githubusercontent.com/46949445/85029959-8f3b0d00-b185-11ea-9e89-1bc6df7aa6a0.png)
proof из figma
![image](https://user-images.githubusercontent.com/46949445/85030076-b09bf900-b185-11ea-8142-c52c7f92480b.png)

**Comment by parunkov** [comment]
А у label какие лишние функции?
Изменять значения элементов формы при нажатии курсором мыши на текст,  устанавливать горячие клавиши на клавиатуре и переходить на активный элемент подобно ссылкам.
Мне кажется это в данном случае не требуется.
