### ISSUE TITLE
Функционал

### ISSUE THREAD

**Issue by kate-fsd** [parunkov/toxin#13]
1. Сделай так чтоб по клику вне дропдаунов, календарей они закрывались

2. Тут должен быть календарь
![image](https://user-images.githubusercontent.com/66846004/86276627-de4d5d00-bbdd-11ea-8f16-b9e51c156e02.png)

3. Здесь когда ты кликаешь по кнопкам +/-  текст в поле должен сразу меняться, как в дропдауне удобства
![image](https://user-images.githubusercontent.com/66846004/86276708-0ccb3800-bbde-11ea-9a92-3e27ddebc55d.png)

4. Пончик должен работать. При наведении должно меняться количество голосов и расширяться соответствующая секция
![image](https://user-images.githubusercontent.com/66846004/86277819-08a01a00-bbe0-11ea-9ea0-5e88ce187452.png)

5. Не работает masked-text-field

**Comment by parunkov** [comment]
Где нужны masked-text-field?

**Comment by kate-fsd** [comment]
Там где есть плэйсхолдер ДД.ММ.ГГГ. Предполагается что пользователь не сможет ввести что то постороннее в эти инпуты, только по маске. Будет хорошо если сделаешь маску не только даты, а с разными параметрами (например банковской карты, паспорта и тд). Параметры можно передать через data-атрибуты.
В date-range - по желанию, можно использовать поля с маской, можно нет. Во втором случае пользователь не должен иметь возможности вводить что то невалидное в инпуты

**Comment by kate-fsd** [comment]
В пончике сделай только так, чтоб по дефолту все были узкими и показывалось общее количество голосов

В room-details при нажатии на кнопку очистить не исчезает вторая дата

)))
![image](https://user-images.githubusercontent.com/66846004/86609473-a581ff00-bfb4-11ea-9631-191080d9a2ec.png)

**Comment by kate-fsd** [comment]
Сейчас после ввода вручную дат в date-range не работает выбор на календаре. Если ты добавил возможность вводить дату руками, то оно должно работать в обе стороны - когда вводишь вручную на календаре должен появиться правильный диапазон, когда выбираешь диапазон на календаре даты должны подставиться в инпуты

**Comment by kate-fsd** [comment]
x-special/nautilus-clipboard
copy
file:///home/kate/%D0%92%D0%B8%D0%B4%D0%B5%D0%BE/Peek%202020-07-15%2021-57.gif

**Comment by kate-fsd** [comment]
На странице registration не работает маска, а на sign-in войти email два раза)

**Comment by kate-fsd** [comment]
Страница landing-page. Ввожу дату, нажимаю enter, меня перебрасывает на другую страницу

**Comment by kate-fsd** [comment]
Календарь в filre-date-dropdown не закрывается по клику вне его

**Comment by kate-fsd** [comment]
В дропдаунах сделай так, чтобы когда все пункты по нулям кнопки очистить не было
