### ISSUE TITLE
Resposive

### ISSUE THREAD

**Issue by kate-fsd** [parunkov/toxin#15]
1. Выглядит плохо
![image](https://user-images.githubusercontent.com/66846004/86277447-5e27f700-bbdf-11ea-89b1-dbe842f2aeae.png)

![image](https://user-images.githubusercontent.com/66846004/86277579-9af3ee00-bbdf-11ea-8fc9-b1365eaca1ca.png)

2. Или сделать полоски короткими или все отцентрировать
![image](https://user-images.githubusercontent.com/66846004/86278338-e5299f00-bbe0-11ea-957a-7b2dbfdfcebb.png)

и форма тут просится в центр)
![image](https://user-images.githubusercontent.com/66846004/86278420-0a1e1200-bbe1-11ea-8699-9b1aa9a9c08d.png)

**Comment by parunkov** [comment]
Карточки не надо резиновые делать? Сделать фиксированную ширину?

**Comment by kate-fsd** [comment]
Если делаешь резиновыми то лишних полосок не должно быть. Можно сделать фиксированными
