### ISSUE TITLE
БЭМ

### ISSUE THREAD

**Issue by kate-fsd** [parunkov/toxin#19]
1. ![image](https://user-images.githubusercontent.com/66846004/87586851-e3d09a00-c6e9-11ea-91e0-9c6742fc5678.png)
Эти заголовки ты сделал частью компонентов, и в для каждого компонента в стилях ты прописываешь одни и те же стили. Если у тебя он многократно повторяется вынеси его в отдельный блок. Можно для добавления заголовков использовать шаблон с блоком https://pugjs.org/language/inheritance.html

2. У блока должен быть основной класс === названию миксина, например не только js-input, но и  просто input

3. input__field_selected что здесь значит selected? Если ты имел ввиду заполненный, то зачем для этого нужен модификатор
input__field_theme_without-hover - то же

4. Ты слишком активно используешь слово theme, оно больше к стилям подходит. Попробуй подбирать более подходящие имена для модификаторов. Например: 
dropdown__counter-button_theme_decrement-inactive
декремент это операция а не тема. А неактивный - состояние, к тому же булевое.
есть еще проблема в этом классе. Зачем здесь и декремент и inactive вместе. Неактивным может быть и плюс и минус

5. ![image](https://user-images.githubusercontent.com/66846004/87591416-f5697000-c6f0-11ea-8131-2b8e346f815c.png)
здесь на одном элементе два разных класса

6. checkbox - у тебя не один input с type checkbox, а группа чекбоксов. Это неправильно

7. Одна кнопка чекбокса - компонент. Выпадающий список с чекбоксами тоже отдельный компонент.
То же самое с тогглами, лайками и тд

8. search-room__rich-wrapper - толстая обертка - неподходящее название
search-room__expandable-wrapper
Когда ты во внешнем блоке используешь другой блок можешь не использовать слово wrapper, а писать так
.form
    .form__input
        .input
    .form__button
        .button

**Comment by kate-fsd** [comment]
В примере все отступы съелись) если не поймешь, напиши

**Comment by kate-fsd** [comment]
Второй пункт не везде соблюдается

**Comment by kate-fsd** [comment]
Опять card__rate-wrapper

Это блок
![image](https://user-images.githubusercontent.com/66846004/88825472-4b014a80-d1d0-11ea-9daa-fb884cd7a0f0.png)
и в юи ките не работает

**Comment by kate-fsd** [comment]
className = item === 'themeArrow' ? className + ' button_translucent_theme_with-arrow' : className;
Если ты не знаешь в чем здесь проблема, почитай документацию БЭМ https://ru.bem.info/methodology/

**Comment by kate-fsd** [comment]
2. 
![image](https://user-images.githubusercontent.com/66846004/89584572-f8193a00-d844-11ea-9743-6d8a0ae3affc.png)
Из документации БЭМ "Невозможно одновременно использовать два одинаковых модификатора с разными значениями"
Разве у тебя не может быть инпут одновременно светлым и с uppercasом? Эти два  модификатора друг другу не противоречат. Если у тебя это действительно два модификатора которые нельзя использовать одновременно, стоит еще подумать об их названиях

3. 
![image](https://user-images.githubusercontent.com/66846004/89587927-3ca7d400-d84b-11ea-8c33-0cb3692af96c.png)
Во первых у тебя есть только один вариант color - purple. В таком случае это скорее булевый модификатор, то есть цветная/не цветная. Во вторых - purple - неудачное название ни для аргумента ни для модификатора. Представь что завтра основной цвет станет красным.

**Comment by kate-fsd** [comment]
не исправил 
![image](https://user-images.githubusercontent.com/66846004/90043550-ef0cea80-dcd4-11ea-9874-9b2819bd2d1c.png)
и зачем здесь i

**Comment by kate-fsd** [comment]
![image](https://user-images.githubusercontent.com/66846004/90420293-7042f380-e0c0-11ea-8976-802cc902520b.png)
Тема светлая и без эффекта наведения - разве нельзя эти два модификатора использовать одновременно?
text_uppercase у тебя других модификаций text нет. Он используется только для дат? Если да - можно вообще его убрать.

**Comment by parunkov** [comment]
theme_without-hover-effect используется в filter-date-dropdown

**Comment by kate-fsd** [comment]
![image](https://user-images.githubusercontent.com/66846004/91090770-3f356680-e65e-11ea-82a8-0de472cb722e.png)

**Comment by kate-fsd** [comment]
Элемент не существует в отрыве от блока
![image](https://user-images.githubusercontent.com/66846004/91091049-b3700a00-e65e-11ea-9f36-9de5c35748e0.png)
