### ISSUE TITLE
package.json

### ISSUE THREAD

**Issue by artamonJr** [parunkov/toxin#2]
1. Убрать поля name, version, description, name, author, lisence.
2. Добавить поле private
3. Для чего у тебя используется скрипт serv?
4. Разнеси зависимости dep и devDep
![image](https://user-images.githubusercontent.com/46949445/77410605-2c2b1b80-6dcc-11ea-901f-87fab0e9735d.png)

**Comment by parunkov** [comment]
Поля name, version, description, name, author, lisence убрал, private добавил. Скрипт serv удалил. dep и devDep разнес. Удалил ненужные файлы и модули.

**Comment by madnessJs** [comment]
поле main тоже лишнее в твоем случае

**Comment by parunkov** [comment]
В package.json убрал main, paginationjs перенес в dep.
В комментариях нужно название коммита повторять или все видно и так?

**Comment by lagunov-artem** [comment]
> В package.json убрал main, paginationjs перенес в dep.
> В комментариях нужно название коммита повторять или все видно и так?

Не нужно. Будет круто если ты в телеграме будешь отписываться, что мол все сделал.
Почему 3 коммита на 1 исправление?
![image](https://user-images.githubusercontent.com/46949445/77552074-2284df00-6ec4-11ea-9e67-bcb4a3b6d3bf.png)

**Comment by parunkov** [comment]
Забыл, что надо #2 написать, пришлось повторить.

**Comment by artamonJr** [comment]
Окей. Отличные названия коммитов, продолжай в том же духе!
