### ISSUE TITLE
Именования

### ISSUE THREAD

**Issue by kate-fsd** [parunkov/toxin#22]
card__a неудачно название элемента

card непонятно что за карточка

.checkbox__custom

**Comment by kate-fsd** [comment]
В компоненте инпут
const {header, type = 'text', name, value, placeholder, text, icon, color, modifiers} = data;
Не очевидно, что цвет именно для иконки

**Comment by kate-fsd** [comment]
if buttonColor === 'purple'
Основной цвет может измениться с фиолетового на красный

**Comment by kate-fsd** [comment]
span.input__name скорее это заголовок

**Comment by kate-fsd** [comment]
input__field_focused, input__field_theme_without-hover-effect подумай еще над именами. Если focused только для ui-kit - можно без него, главное чтобы при наведении и фокусе совпадало с макетом.

**Comment by kate-fsd** [comment]
В инпуте
![image](https://user-images.githubusercontent.com/66846004/91874360-d021c880-ec82-11ea-86e0-51b1e66e5b5f.png)
больше стилей для theme light нет, и если не заглядывать в файл стилей, никогда не угадаешь, что это за тема. Неудачное имя. А зачем он добавлен? Там плейсхолдеры вроде везде светлые

**Comment by parunkov** [comment]
Есть и темные плесхолдеры.
