### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by kate-fsd** [parunkov/toxin#25]
1. Здесь ты дублируешь свойства. Еще в модификаторах кнопки много где повторяется display: block. Если это свойство является дефолтным, выноси его в класс button. А уже в модификаторах если требуется другое - переопределяй. Если есть подобные ошибки в других местах, исправь тоже
![image](https://user-images.githubusercontent.com/66846004/89583331-cf904080-d842-11ea-985b-cc19f33fe480.png)

2. Не прописывай вручную автопрефиксы, установи автопрефиксер

**Comment by kate-fsd** [comment]
button_theme_light
position: relative; прописываешь второй раз

button_theme_text
background: $white;
![image](https://user-images.githubusercontent.com/66846004/90041892-9b999d00-dcd2-11ea-894b-7fdb1945486d.png)

**Comment by kate-fsd** [comment]
![image](https://user-images.githubusercontent.com/66846004/90047180-292cbb00-dcda-11ea-9f3d-5a0db209b28b.png)
везде разные отсупы, приведи все к одному виду

**Comment by kate-fsd** [comment]
Вертикальные отступы до сих пор разные

**Comment by kate-fsd** [comment]
.checkbox {
  display: block;
  position: relative;
  vertical-align: top;

vertical-align здесь не работает, почитай про это свойство

**Comment by kate-fsd** [comment]
Опять отступы. Почитай эти правила https://github.com/airbnb/css#formatting

**Comment by kate-fsd** [comment]
.input__text  в стилях одновременно vertical-align и display: block;
Исправляй замечания сразу во всем проекте, а не только в том месте на которое указываю

**Comment by kate-fsd** [comment]
![image](https://user-images.githubusercontent.com/66846004/91479282-df330000-e8a9-11ea-846c-2d3c1d97af97.png)

**Comment by kate-fsd** [comment]
.button_theme_text  ему не нужна высота

**Comment by kate-fsd** [comment]
.button_theme_with-arrow::after 
свойства display и word-break

**Comment by kate-fsd** [comment]
.button_color_gray  opacity

**Comment by kate-fsd** [comment]
У form-elements__btn убираю ширину и получаю
![image](https://user-images.githubusercontent.com/66846004/91878393-e3836280-ec87-11ea-85cf-63640e0d3c36.png)

а когда убираю еще inline-block
![image](https://user-images.githubusercontent.com/66846004/91878446-fa29b980-ec87-11ea-9c6e-771a942edd6b.png)

Сделай так, чтобы размеры кнопки задавались в ней самой, и кнопка сама по себе имела нормальный вид

**Comment by parunkov** [comment]
word-break нужен, без него едет верстка

**Comment by kate-fsd** [comment]
![image](https://user-images.githubusercontent.com/66846004/92512511-8c493900-f217-11ea-8e3b-3938e7d3e8d0.png)

**Comment by kate-fsd** [comment]
> а когда убираю еще inline-block

лучше эти кнопки не делать такими большими - 350px. Они везде маленькие, растянутая только со стрелкой

**Comment by kate-fsd** [comment]
Для текстовых убери min-width, max-width
