### ISSUE TITLE
commits

### ISSUE THREAD

**Issue by lagunov-artem** [parunkov/toxin#3]
Ужасные названия коммитов (шрифты, то же)
![image](https://user-images.githubusercontent.com/46949445/77416180-a2cc1700-6dd4-11ea-999c-3c93d8af148a.png)
Именуй нормально и пиши конкретно что делал. Вот 'убрал теги без классов' хорошее название. Ориентируйся на этот подход

**Comment by parunkov** [comment]
Понятно, постараюсь.
