### ISSUE TITLE
pp

### ISSUE THREAD

**Issue by artamonJr** [parunkov/toxin#4]
![image](https://user-images.githubusercontent.com/46949445/77514135-5392ee80-6e87-11ea-8d79-a0804c14d7b8.png)

**Comment by parunkov** [comment]
Здесь расхождения в ширине - у макета 1440px а по ТЗ - от 320px до 1920px. При ширине 1440px верстка должна совпасть с макетом, а на 1920px она растянута. Для проверки поменял значение переменной, потом можно будет обратно поменять.

**Comment by artamonJr** [comment]
> Здесь расхождения в ширине - у макета 1440px а по ТЗ - от 320px до 1920px. При ширине 1440px верстка должна совпасть с макетом, а на 1920px она растянута. Для проверки поменял значение переменной, потом можно будет обратно поменять.

Со стажером тоже это обсуждали) Не нужно ничего менять обратно, лучше оставить ширину контента такой как есть при ширине страницы 1440px.

**Comment by artamonJr** [comment]
![image](https://user-images.githubusercontent.com/46949445/77649253-98e41880-6f7a-11ea-933b-c45fa852e8e7.png)

**Comment by parunkov** [comment]
Отклонения в 5px допустимы?

**Comment by artamonJr** [comment]
> Отклонения в 5px допустимы?

да, не больше

**Comment by artamonJr** [comment]
Кнопку подравняй
![image](https://user-images.githubusercontent.com/46949445/80500133-775dbe80-8976-11ea-8d8d-18ee2678e904.png)

![image](https://user-images.githubusercontent.com/46949445/80500354-c6a3ef00-8976-11ea-9ebc-bd1ba4f5fbbe.png)

Тоже кнопка
![image](https://user-images.githubusercontent.com/46949445/80500513-f94de780-8976-11ea-92dd-10d4c65fee29.png)

Страница регистрации
![image](https://user-images.githubusercontent.com/46949445/80500596-11be0200-8977-11ea-993e-3a5e861add0f.png)
![image](https://user-images.githubusercontent.com/46949445/80500639-1be00080-8977-11ea-9372-f5785ac570d0.png)

Одна комната

**Comment by parunkov** [comment]
Там различие небольшое в макетах (с дропдауном гостей и без него).

**Comment by parunkov** [comment]
Здесь есть отличие в футере в макете.

**Comment by artamonJr** [comment]
> Здесь есть отличие в футере в макете.

Где?

Нижняя часть футера на странице "Войти" 70px по высоте, на странице "Регистрация" 69.37. У тебя на странице "Регистрация" такие различия в нижней части футера. Тут явно косяк за тобой
![image](https://user-images.githubusercontent.com/46949445/80947156-3cd1a700-8df8-11ea-9461-c13b1874e6e9.png)

Поправь на этой странице везде, много косяков
![image](https://user-images.githubusercontent.com/46949445/80947523-fc265d80-8df8-11ea-8c17-87e85fd6786b.png)

**Comment by parunkov** [comment]
У меня 72px оба. Это в макете косяк - там верхняя часть футера разная по высоте: у "Регистрации" - 368,64, у "Войти" - 372.

**Comment by parunkov** [comment]
![Новый-1](https://user-images.githubusercontent.com/48278719/81031330-57ae2500-8ea5-11ea-91a2-b4d89e1dc3ed.jpg)
У меня так.

**Comment by parunkov** [comment]
Пагинацию на этой станице ужал - она не влезает в одну строку.

**Comment by artamonJr** [comment]
> У меня 72px оба. Это в макете косяк - там верхняя часть футера разная по высоте: у "Регистрации" - 368,64, у "Войти" - 372.

У вас обоих косяки, и у тебя и у макета) Футер отличается только на странице регистрации, поэтому поправь, чтобы он был в пп на других страницах, а тут пускай так будет.

> У меня так

Покажи настройки страницы и расширения пп

> Пагинацию на этой станице ужал - она не влезает в одну строку

Должна влезть)

**Comment by parunkov** [comment]
![Новый-2](https://user-images.githubusercontent.com/48278719/81363386-a7d2f480-90fc-11ea-8d12-ecd4ae040927.jpg)
Настройки.

**Comment by parunkov** [comment]
![Новый-3](https://user-images.githubusercontent.com/48278719/81363567-157f2080-90fd-11ea-8a29-83048aacfc9b.jpg)
Футер.

**Comment by artamonJr** [comment]
> У вас обоих косяки, и у тебя и у макета) Футер отличается только на странице регистрации, поэтому поправь, чтобы он был в пп на других страницах, а тут пускай так будет.

не исправил. Страница входа
![image](https://user-images.githubusercontent.com/46949445/81407384-f952a200-9143-11ea-9359-c004e0b9914e.png)

Размеры картинки для страницы элементов форм такие же?
![image](https://user-images.githubusercontent.com/46949445/81407590-5b130c00-9144-11ea-8f0a-54a4cd4d3875.png)
Дропдауны сейчас в порядке, поехала средняя колонка
![image](https://user-images.githubusercontent.com/46949445/81407691-80a01580-9144-11ea-917c-2342000be9fd.png)

Страницы хедеров и футеров
![image](https://user-images.githubusercontent.com/46949445/81407838-bf35d000-9144-11ea-8008-bf59db88bb0b.png)

**Comment by parunkov** [comment]
Я в form_elements не менял ничего, картинка такая же - 1440х1853,  экспортировал новую из макета - ничего не изменилось, все совпадает у меня.

**Comment by artamonJr** [comment]
> Я в form_elements не менял ничего, картинка такая же - 1440х1853, экспортировал новую из макета - ничего не изменилось, все совпадает у меня.

Тогда оставим этот момент на конец ревью первого проекта. Попрошу коллегу посмотреть

**Comment by parunkov** [comment]
Посмотрел на другом компьютере form_elements - не совпадает. Исправил на нем. Видимо еще от монитора зависит, размеры и разрешение разное у мониторов.

**Comment by artamonJr** [comment]
Футер на странице регистрации
![image](https://user-images.githubusercontent.com/46949445/82055557-582a9500-96c9-11ea-8fbd-5867e2c6c56d.png)
