### ISSUE TITLE
bugs/ui

### ISSUE THREAD

**Issue by artamonJr** [parunkov/toxin#5]
Ширина макета должна тянуться до 1920, а у тебя до 1440

Хедер
1. Стрелочка у пункта с подменю тоже интерактивный элемент
2. 8 [пункт](https://github.com/fullstack-development/front-end-best-practices/blob/master/CSS/errors.md) стандартов
3. Кнопка не по макету выполнена
![image](https://user-images.githubusercontent.com/46949445/78236576-d8fb4c00-74e2-11ea-9c1d-63f4314ff608.png)

**Comment by artamonJr** [comment]
Хедер
1. Стрелочка у пункта с подменю тоже интерактивный элемент
2. 8 [пункт](https://github.com/fullstack-development/front-end-best-practices/blob/master/CSS/errors.md) стандартов
3. Кнопка не по макету выполнена
![image](https://user-images.githubusercontent.com/46949445/78236576-d8fb4c00-74e2-11ea-9c1d-63f4314ff608.png)

**Comment by artamonJr** [comment]
![image](https://user-images.githubusercontent.com/46949445/78570737-08d18900-782e-11ea-81fc-121f333c9acd.png)


Вообще не юзабельное меню, очень странное поведение. Нужно переделать
![Peek 2020-04-06 17-42](https://user-images.githubusercontent.com/46949445/78570769-0ff89700-782e-11ea-87ef-27e5203a1108.gif)

Кнопка вываливается наружу + меню выглядит некрасиво)
![image](https://user-images.githubusercontent.com/46949445/78571192-990fce00-782e-11ea-98e0-ab8333ff7441.png)

Явно напрашивается мобильное меню)
![image](https://user-images.githubusercontent.com/46949445/78571297-b349ac00-782e-11ea-8491-ff393b3c35d3.png)

Текст из кнопки вывалился
![image](https://user-images.githubusercontent.com/46949445/78571419-d7a58880-782e-11ea-9dbe-f6f6b27273f4.png)

Почему курсор мигает после стрелки? Вообще странное поведение)
![image](https://user-images.githubusercontent.com/46949445/78571663-1e937e00-782f-11ea-9296-5a9a911941ae.png)

Почему 1 заголовок ссылка, а 2 нет?
![image](https://user-images.githubusercontent.com/46949445/78571879-69ad9100-782f-11ea-9842-09481ec068b4.png)

При добавлении колонки в футер едет верстка
![image](https://user-images.githubusercontent.com/46949445/78572264-eb052380-782f-11ea-99b6-d1f2fa30df3b.png)

**Comment by parunkov** [comment]
Я заменил 1920px на 1440px для проверки на pixel perfect. Потом верну обратно.

**Comment by parunkov** [comment]
Непонятно с hover (8 пункт стандартов). При наведении курсора на пункт меню должно появляться выпадающее подменю? Или при клике? При убирании курсора с пункта меню, впадающее подменю должно пропадать?

**Comment by parunkov** [comment]
Сделал выпадающее меню по клику, так вроде лучше работает. При наведении курсора оно выскакивает когда не надо.

**Comment by artamonJr** [comment]
> Я заменил 1920px на 1440px для проверки на pixel perfect. Потом верну обратно.

Не пойдет) Используй для этого возможность тянуть окно браузера

**Comment by parunkov** [comment]
Скажи плиз, почему ты принял такое решение, что это ссылка?
Я считаю, что это заголовок, ссылки не должно быть.  Вопрос понял так, что надо поставить ссылку и поставил (на заглушку).

**Comment by artamonJr** [comment]
Выровни по горизонтали
![image](https://user-images.githubusercontent.com/46949445/78991466-ac2de100-7b41-11ea-9bb6-88e980161c35.png)

Стрелка прилипла к тексту
![image](https://user-images.githubusercontent.com/46949445/78991518-c798ec00-7b41-11ea-8367-78ef85d2023f.png)

Не понятно где пункты меню, а где подменю
![image](https://user-images.githubusercontent.com/46949445/78991549-d97a8f00-7b41-11ea-96de-a02393d5bcae.png)

Переполнение
![image](https://user-images.githubusercontent.com/46949445/78991599-f7e08a80-7b41-11ea-91f8-4d060725bfcd.png)

Неправильно поведение у бургера. После нажатия он должен давать знать, что меню открыто. Поизучай пример с меню на сайте apple

**Comment by parunkov** [comment]
По поводу ссылки и заголовка. Там по смыслу просто пользователь должен подписаться - ввести e-mail и отправить, весь функционал для этого есть ниже и отдельная страница для этого не нужна. 
Хотя конечно и возможна какая-то дополнительная информация о подписке на отдельной странице, но для этого нужно знать всю карту сайта.

**Comment by artamonJr** [comment]
Замени черную фавиконку на знак отеля из логотипа

**Comment by parunkov** [comment]
По поводу ссылок - страницы "О нас" и "Служба поддержки" по моему должны быть. "Навигация" - скорее заголовок, чем ссылка.

**Comment by artamonJr** [comment]
Крестик не поправил
![image](https://user-images.githubusercontent.com/46949445/79336538-9c8d0e80-7f2c-11ea-806e-3871736f87f3.png)

> По поводу ссылок - страницы "О нас" и "Служба поддержки" по моему должны быть. "Навигация" - скорее заголовок, чем ссылка

Хм, возможен конечно такой вариант, но что у тебя будет, когда ты перейдешь на страницу О нас, к примеру? У тебя вся доступная информация представлена в виде ссылок под заголовоком

**Comment by parunkov** [comment]
Ссылки убрал, возможно "Связь с нами" это и есть "СЛУЖБА ПОДДЕРЖКИ"

**Comment by artamonJr** [comment]
такое решение не подойдет для решения этого вопроса. В стандартах есть статья где можно почитать как это делается
![image](https://user-images.githubusercontent.com/46949445/79568185-11dc1900-80be-11ea-9e64-ae456dcfa6ab.png)

Если уж ты реализовал выпадающее меню, то будем его шлифовать) Вот баг + кнопки опять же таки слишком растянуты
![Peek 2020-04-17 15-17](https://user-images.githubusercontent.com/46949445/79568478-929b1500-80be-11ea-9c00-d9e6ce99e997.gif)

**Comment by artamonJr** [comment]
![image](https://user-images.githubusercontent.com/46949445/79966075-8f74a000-8495-11ea-80dc-0c565b2b55b2.png)
Где исправления по этому правилу?
Смотри. Если у тебя в контентном блоке мало контенте, или его вообще нет, как в скриншоте, то футер у тебя должен быть прижат к низу страницы. у тебя сейчас нет этого поведения
![image](https://user-images.githubusercontent.com/46949445/79965805-2a20af00-8495-11ea-935d-956698c3798c.png)

> Ну это не катит точно)) лучше измени фон на подходящий
Я имел ввиду фон страницы измени на нормальный. Чтобы не нужно было делать фоны у текста, это выглядит не красиво

Горизонтальная полоса прокрутки
![image](https://user-images.githubusercontent.com/46949445/79966519-3a855980-8496-11ea-8fb1-9f1ff59ae134.png)

Кнопки слиплись и вывалились
![image](https://user-images.githubusercontent.com/46949445/79966614-5ab51880-8496-11ea-9aaf-4826052cb63b.png)

Добавь отступы между секциями
![image](https://user-images.githubusercontent.com/46949445/79966802-a5cf2b80-8496-11ea-97e9-4d422f7e20fe.png)

**Comment by parunkov** [comment]
Также, по наведению на поле дропдауна курсор должен быть обычным, в виде стрелки.

Имеется в виду стрелка справа в инпуте? Это кликабельный элемент, по стандартам должен быть pointer.

**Comment by artamonJr** [comment]
Стрелочка на текст налезла
И еще погляди, у тебя на ширине 316 текст в инпутах становится строчным)) это не обязательно исправлять
![image](https://user-images.githubusercontent.com/46949445/80225132-54b86680-8653-11ea-8d5f-aaf83a97d860.png)

По дропдаунам. Вот в этом дропдауне у тебя все отлично сделано. По наведению на лейбл нет поинтера, по наведению на инпут обычный курсор и нет границы, по наведению на стрелочку появляется поинтер, нет возможности писать в инпуте. Ориентируйся на него, в дропдаунах.
![image](https://user-images.githubusercontent.com/46949445/80225698-12dbf000-8654-11ea-936d-af4c17537015.png)

Кнопка 'очистить' не пропадает
![Peek 2020-04-24 17-52](https://user-images.githubusercontent.com/46949445/80225884-5d5d6c80-8654-11ea-8f8f-21e52085c581.gif)

По наведению на сегодняшний день он не должен менять свой стиль
![image](https://user-images.githubusercontent.com/46949445/80226317-e1afef80-8654-11ea-81b9-98af470ea2a8.png)

Если выбираем сегодняшний день он не должен менять стиль
![image](https://user-images.githubusercontent.com/46949445/80226615-466b4a00-8655-11ea-8f26-df61bcaabc0b.png)

Текст в крайней правой дате тоже должен быть белым
И, странно, при такой настройке, по наведению на 30 число, текст не меняет цвет, а по наведению на 1, меняет
![image](https://user-images.githubusercontent.com/46949445/80226472-11f78e00-8655-11ea-8ca1-7d847201b9c9.png)

Тут на 1 скрине все ок, а на втором цвет текста другой
![image](https://user-images.githubusercontent.com/46949445/80226733-6a2e9000-8655-11ea-81e7-78b8216dc7f6.png)
![image](https://user-images.githubusercontent.com/46949445/80226747-6f8bda80-8655-11ea-9fe0-8cbd16f29957.png)

По добавлении в кнопку текста, растет и другая
![image](https://user-images.githubusercontent.com/46949445/80227501-5e8f9900-8656-11ea-9966-f812c8f91604.png)

Переполнение
![image](https://user-images.githubusercontent.com/46949445/80227532-6e0ee200-8656-11ea-909e-3f2f8f330e80.png)

**Comment by artamonJr** [comment]
Область нажатия вылазиет за инпут
![image](https://user-images.githubusercontent.com/46949445/80499135-4204a100-8975-11ea-8a7c-9f61462b1bca.png)

Сегодняшний день не должен менять свой стиль
![image](https://user-images.githubusercontent.com/46949445/80499413-9f005700-8975-11ea-8560-8b429806357c.png)

**Comment by artamonJr** [comment]
Убери хедер и футер со стартовой страницы, и обнови readme) Оставь в ридми только одну страницу

**Comment by artamonJr** [comment]
Последний косячок с календарем)
![Peek 2020-05-04 11-26](https://user-images.githubusercontent.com/46949445/80948135-2f1d2100-8dfa-11ea-8e39-b84b1eef45c6.gif)

**Comment by parunkov** [comment]
Дату рождения можно заполнить, там input type="date"

**Comment by parunkov** [comment]
Зеленая рамка у комнаты из макета

**Comment by artamonJr** [comment]
Календарь не поправил( Если не понятно, что именно нужно править, напиши в телеграмм
![Peek 2020-05-07 16-51](https://user-images.githubusercontent.com/46949445/81302622-46227400-9083-11ea-8225-71bfffee5703.gif)

Текст у кнопки на стр. входа прилипает к краям
![image](https://user-images.githubusercontent.com/46949445/81303148-0019e000-9084-11ea-99de-1f24da44e768.png)

Текст съехал
![image](https://user-images.githubusercontent.com/46949445/81303219-16c03700-9084-11ea-90c1-e30866ff8128.png)

> Дату рождения можно заполнить, там input type="date". Переделать на type="text"?

Не, переделывать не нужно, тут как раз и нужен этот тип. Оставь как есть

> Зеленая рамка у комнаты из макета

Можешь пруф показать?

Почему по буквам переносится заголовок?
![image](https://user-images.githubusercontent.com/46949445/81304372-a6b2b080-9085-11ea-9e06-014dcd59fe96.png)

Убери показывание календаря здесь. Я думаю, необязательно его тут реализовывать. Или хочешь оставить? Придется тогда ошибки исправлять
![image](https://user-images.githubusercontent.com/46949445/81304898-5daf2c00-9086-11ea-9496-ffbcd539ec02.png)

**Comment by parunkov** [comment]
![Новый-1](https://user-images.githubusercontent.com/48278719/81367985-1e292400-9108-11ea-8d02-32a2ffb3dfc2.jpg)
Макет.

**Comment by parunkov** [comment]
Перенос по буквам потому, что не входит "Константинопольский".

**Comment by artamonJr** [comment]
Странно, вот тоже в макете смотрю. Может из-за линеек, которые у тебя включены... В общем, не должно быть рамки зеленой
![image](https://user-images.githubusercontent.com/46949445/81408441-e5a83b00-9145-11ea-901c-461fc48214b9.png)

> Перенос по буквам потому, что не входит "Константинопольский"

понял, но так тоже нельзя оставлять, придумай что-то с этим

**Comment by artamonJr** [comment]
Все еще календарь(
![Peek 2020-05-14 13-06](https://user-images.githubusercontent.com/46949445/81921793-d4e34380-95e3-11ea-8d2d-4e29e907400b.gif)

Почему стрелка тут поворачивается, если календарь не открывается?
![image](https://user-images.githubusercontent.com/46949445/81922862-67d0ad80-95e5-11ea-900e-583fb0debbbf.png)

Стрелочки - hover-эффект
![image](https://user-images.githubusercontent.com/46949445/81923021-af573980-95e5-11ea-93c8-324ae3d5d0f7.png)

Отступ вниз у пагинации увеличить нужно
![image](https://user-images.githubusercontent.com/46949445/81923277-14ab2a80-95e6-11ea-95d4-638c4650695d.png)

Странная область нажатия на стрелку. Пространство для нажатия внизу меньше чем наверху
![Peek 2020-05-14 13-27](https://user-images.githubusercontent.com/46949445/81923788-dd894900-95e6-11ea-8e05-a11056fb93d2.gif)

Компонент не по макету выполнен
И, странно, с точки зрения ui по клику на кнопку не прибавлять/убавлять кол-во лайков)) Нужно поправить
![image](https://user-images.githubusercontent.com/46949445/81924132-5dafae80-95e7-11ea-88a8-54d7c5629ca8.png)

Где кол-во отзывов?
![image](https://user-images.githubusercontent.com/46949445/81924290-994a7880-95e7-11ea-8f22-74d67ff03c72.png)

Компонент не по макету выполнен
![image](https://user-images.githubusercontent.com/46949445/81924460-d7479c80-95e7-11ea-8905-666af8c8afdc.png)

На маленьком экране, некрасиво смотрятся 3 подряд идущие картинки. Слишком много места занимают
![image](https://user-images.githubusercontent.com/46949445/81924895-66ed4b00-95e8-11ea-9199-bcd4ea82aa32.png)

Горизонтальная полоса прокрутки появляется несколько раз от 320 до 1920
![image](https://user-images.githubusercontent.com/46949445/81925072-ac117d00-95e8-11ea-931b-5e7fc0007b38.png)

Переполнение
![image](https://user-images.githubusercontent.com/46949445/81925776-a10b1c80-95e9-11ea-8052-4996c3fccd3e.png)

**Comment by artamonJr** [comment]
Календарь :(

**Comment by artamonJr** [comment]
![Peek 2020-05-20 16-09](https://user-images.githubusercontent.com/46949445/82449711-52132a80-9ab4-11ea-99c6-bf217abd8f37.gif)

**Comment by artamonJr** [comment]
![Peek 2020-06-08 11-47](https://user-images.githubusercontent.com/46949445/84010816-dd7a3000-a97d-11ea-88f3-37b86354fa12.gif)

**Comment by artamonJr** [comment]
Опять календарь(
И проверь еще раз календарь в соответствии с макетом. Имеются отклонения в цветах
![1](https://user-images.githubusercontent.com/46949445/84145044-e17f7e00-aa61-11ea-939a-ef4a6f31e3cb.gif)

**Comment by artamonJr** [comment]
Посмотри повнимательнее эти места
![Снимок экрана от 2020-06-11 11-51-40](https://user-images.githubusercontent.com/46949445/84365826-af455c00-abda-11ea-8e1c-11427bc322f2.png)

Еще немного календаря
Кнопка "Очистить" не пропадает когда нет выделенных дат
На кнопке "Применить" должен быть ховер эффект по аналогии с дропдауном
![Peek 2020-06-11 11-58](https://user-images.githubusercontent.com/46949445/84366131-19f69780-abdb-11ea-94ba-d18b9bf21659.gif)

**Comment by artamonJr** [comment]
Тут не должно быть hover-эффекта
![image](https://user-images.githubusercontent.com/46949445/84767287-d5a03880-afda-11ea-9250-13875d942096.png)

**Comment by artamonJr** [comment]
Не должно быть возможности тут писать самому текст
![image](https://user-images.githubusercontent.com/46949445/85030433-20aa7f00-b186-11ea-9693-548e85ef64a8.png)
