### ISSUE TITLE
html/pug

### ISSUE THREAD

**Issue by artamonJr** [parunkov/toxin#7]
Отсутствуют мета-теги keywords, description

Не пойдет такой titile. Придумай нормальное название для страницы
![image](https://user-images.githubusercontent.com/46949445/82061587-975ce400-96d1-11ea-9ab7-5079415d6a62.png)

**Comment by artamonJr** [comment]
Копни чуть глубже по этому вопросу. Пока не подойдет такое содержимое
![image](https://user-images.githubusercontent.com/46949445/82212859-e5652800-991b-11ea-8fcf-550bfc201d23.png)

**Comment by parunkov** [comment]
Keywords  не актуален вроде сейчас, зачем его заполнять?

**Comment by parunkov** [comment]
Лого я сделал фоном и вставил через inline-svg в css для ускорения загрузки сайта. Если сделать img надо его в отдельный файл выделять?

**Comment by parunkov** [comment]
.header__active - номер активной страницы в меню. На страницах сайта нет их, поэтому -1.
В ui_kit есть активная страница - там 0. В разметке его вставил для того, чтобы из миксина pug передать в скрипт, по другому не получилось.

**Comment by parunkov** [comment]
Дополнительный div в подменю не получилось убрать, без него серый фон на всю ширину получается - некрасиво.

**Comment by parunkov** [comment]
.page__space - сделал пробел для того чтобы прижать футер к низу страницы, а хедер и майн к верху. Без него большой отступ получается между хедером и майн - плохо смотрится.

**Comment by artamonJr** [comment]
> Keywords не актуален вроде сейчас, зачем его заполнять?

Я бы сказал, "не так актуален", но знать как и зачем его использовать - нужно. Содержание keywords не только про "слова", а также про фразы. Сейчас у тебя есть keyword - поиск, к примеру. Какое отношение это слово имеет к твоему сайту? Поиск может быть, пропавших животных или еще чего
![image](https://user-images.githubusercontent.com/46949445/82450469-686db600-9ab5-11ea-9d3c-c40c63b16489.png)

Вот description вполне неплох тут
![image](https://user-images.githubusercontent.com/46949445/82450771-cb5f4d00-9ab5-11ea-97c8-168e6edeccbd.png)

> Лого я сделал фоном и вставил через inline-svg в css для ускорения загрузки сайта. Если сделать img надо его в отдельный файл выделять?

Да

> .header__active - номер активной страницы в меню

А какой толк у тебя от активной страницы, если не работает переключение страниц? Ты, мне кажется, не очень понимаешь как описать логику переключения активной страницы. Или понимаешь, но плохо. В этом задании не требуется реализовывать подобный функционал, поэтому ограничься, тем, что навесь просто класс на активный пункт меню. А этот .header__active-page-number убери плиз)

> Дополнительный div в подменю не получилось убрать

Его можно, и даже нужно убрать, нужно просто немного постараться)

> .page__space - сделал пробел для того чтобы прижать футер к низу страницы

Нужно найти способ, без добавления доп. тегов) В статье, у нас в стандартах, все же расписано хорошо, зачем изобретать кривой велосипед?)
