### ISSUE TITLE
bem

### ISSUE THREAD

**Issue by artamonJr** [parunkov/toxin#8]
Не может существовать класса элемента без класса блока
![image](https://user-images.githubusercontent.com/46949445/82061832-e3a82400-96d1-11ea-89bb-3158a02acf4d.png)

Оу, вообще не по бем структура)
![image](https://user-images.githubusercontent.com/46949445/82061932-05a1a680-96d2-11ea-8d0c-8a6742143986.png)

Я думаю тебе стоит почитать про [бем](https://ru.bem.info/methodology/quick-start/)

Стиль именования, у нас в команде, [оригинальный](https://ru.bem.info/methodology/naming-convention/#%D0%BF%D1%80%D0%B0%D0%B2%D0%B8%D0%BB%D0%B0-%D1%84%D0%BE%D1%80%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F-%D0%B8%D0%BC%D0%B5%D0%BD)

**Comment by artamonJr** [comment]
Каждый блок = mixin. Т.е. тут, у тебя блоки должны строится из 2-ух миксинов. mixin page и mixin landing
![image](https://user-images.githubusercontent.com/46949445/82213012-29f0c380-991c-11ea-9bb9-60caf48de543.png)

Почему ты назвал этот блок page-header? У тебя есть еще какой-то хедер?
![image](https://user-images.githubusercontent.com/46949445/82213972-b059d500-991d-11ea-99c0-fbe352303a5b.png)

На какой вопрос должно отвечать название блока? На какой вопрос отвечает название блока у тебя?
![image](https://user-images.githubusercontent.com/46949445/82214120-f9aa2480-991d-11ea-9cfb-cc0c40252aad.png)

Не пойдут такие названия
![image](https://user-images.githubusercontent.com/46949445/82214965-48a48980-991f-11ea-992a-e606c46543c9.png)

Не понятно, что ты тут хотел донести модификатором big. Переименуй название модификатора, чтобы было понятно, посмотрев на код, о чем примерно идет речь
![image](https://user-images.githubusercontent.com/46949445/82215393-092a6d00-9920-11ea-8d42-96b7488cd0bc.png)

**Comment by parunkov** [comment]
Есть блок header, он входит в страницу headers-footers и в блок page-header (там разное содержимое). Блок page-header входит в страницы сайта (чтобы не повторять код).

**Comment by artamonJr** [comment]
Плохая завязка блоков тут получается, Блок1 -> Блок2 -> Элемент блока1
![image](https://user-images.githubusercontent.com/46949445/82454147-18452280-9aba-11ea-9810-25c91dc09ba1.png)
И, смотри, ты используешь page__container и внутри хедера и main'а. А не лучше ли будет вынести этот блок и уже внутрь него вложить header с main? Получится один блок, вместо двух

> Есть блок header, он входит в страницу headers-footers и в блок page-header (там разное содержимое). Блок page-header входит в страницы сайта (чтобы не повторять код)

Вообще не понял) У тебя есть один только header на сайте, поэтому убери всякие другие
