### ISSUE TITLE
project structure

### ISSUE THREAD

**Issue by artamonJr** [parunkov/toxin#9]
Удали все неиспользуемые ветки в репозитории

Зачем нужна эта папка?
![image](https://user-images.githubusercontent.com/46949445/82059494-ca51a880-96ce-11ea-9c7d-9bac3cd2cf3a.png)

А этот файл?
![image](https://user-images.githubusercontent.com/46949445/82059683-0c7aea00-96cf-11ea-82a6-27ab81484ee5.png)

Лучше переименовать в src, тк это общепринятое название
![image](https://user-images.githubusercontent.com/46949445/82059554-db021e80-96ce-11ea-8ecd-5c7163682cf0.png)

Зачем этот файл?
![image](https://user-images.githubusercontent.com/46949445/82060066-87dc9b80-96cf-11ea-92e1-c93ed97d86f9.png)

По умолчанию, названия всех файлов и папок пишутся тоже в стиле кебаб-кейс, с маленькой буквы (то-есть-вот-так-вот)
![image](https://user-images.githubusercontent.com/46949445/82060286-d7bb6280-96cf-11ea-97ec-a71793591637.png)
![image](https://user-images.githubusercontent.com/46949445/82060655-557f6e00-96d0-11ea-85f2-0075455d731f.png)

**Comment by parunkov** [comment]
Файл favicons.js создан генератором фавиконок, нужен он или нет я не знаю.

**Comment by parunkov** [comment]
В папке _auxiliary я храню разные вспомогательные файлы, например картинки для проверки pixel perfect. Для проекта она не нужна, но пользоваться удобно. Можно оставить пока, а в конце удалить?

**Comment by artamonJr** [comment]
> В папке _auxiliary я храню разные вспомогательные файлы, например картинки для проверки pixel perfect. Для проекта она не нужна, но пользоваться удобно. Можно оставить пока, а в конце удалить?

Конечно

**Comment by artamonJr** [comment]
> Файл favicons.js создан генератором фавиконок, нужен он или нет я не знаю.

Нужно разобраться, и решить что делать) Нужно понимать что и зачем ты делаешь в работе. Google всегда придет на помощь в этом вопросе)

**Comment by parunkov** [comment]
Файл favicons.js нужен, без него вебпак выдает ошибку при компиляции. В билде его нет.
